// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://cfqnlejmlzpzrdzjkyrj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImNmcW5sZWptbHpwenJkempreXJqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDg5ODc1OTYsImV4cCI6MjA2NDU2MzU5Nn0.Uocc1fWbgjy5YLYlAZPzLKRVDow2dWkvXgRSjjdEWH0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});